
service: echobot

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  region: eu-west-1

functions:
  webhookFunc:
    handler: index.handler
    events:
      - http:
          method: POST
          path: v1/webhook/{serviceName}

plugins:
  - serverless-offline