module.exports = {
    kik: require('./kik'),
    line: require('./line'),
    messenger: require('./messenger'),
    skype: require('./skype'),
    telegram: require('./telegram'),
    twilio: require('./twilio'),
    oxygen8: require('./oxygen8'),
    mitto: require('./mitto'),
    loopback: require('./loopback'),
    chatfire: require('./chatfire'),
    viber: require('./viber'),
    whatsapp: require('./whatsapp'),
    nexmo: require('./nexmo'),
    wechat: require('./wechat'),
}
